plugins {
	id 'base'
}

version = project.mod_version
group = project.maven_group

tasks.named("build") {
	dependsOn(":mod-fabric:build")
}

tasks.named("clean") {
	dependsOn(":mod-fabric:clean")
}

tasks.register("runClient") {
	group = "fabric"
	description = "Runs the Fabric client from the mod-fabric module."
	dependsOn(":mod-fabric:runClient")
}
