package globe.world.network;

public enum PacketPolicyCategory {
    CHUNK_OWNER,
    BLOCK_NEAREST_ALIAS,
    BLOCK_LOADED_ALIAS_FANOUT,
    WORLD_EVENT_NEAREST_ALIAS,
    WORLD_EVENT_LOADED_ALIAS_FANOUT,
    ENTITY_NEAREST_ALIAS,
    NAVIGATION_UI_NEAREST_ALIAS,
    RELATIVE_OR_NON_POSITION_NOOP,
    INTENTIONALLY_UNSUPPORTED
}
