plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = "globe-world-fabric-mod-mc${project.minecraft_version}"
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"globe-world" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.10.2"
}

processResources {
	def version = project.version
	def resourceProperties = [
			version: version,
			mod_author: project.mod_author,
			mod_homepage: project.mod_homepage,
			mod_sources: project.mod_sources,
			loader_version: project.loader_version,
			minecraft_version: project.minecraft_version,
			java_version: project.java_version
	]
	inputs.properties resourceProperties

	filesMatching("fabric.mod.json") {
		expand resourceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = project.java_version.toInteger()
}

tasks.withType(Test).configureEach {
	useJUnitPlatform()
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}

jar {
	def projectName = base.archivesName.get()
	inputs.property "projectName", projectName

	if (rootProject.file("LICENSE").exists()) {
		from(rootProject.file("LICENSE")) {
			rename { "${it}_$projectName"}
		}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
}
